# Site settings
title: 落影汐雾
subtitle: 在时间线渐渐模糊的此时此刻
description: 
baseurl: # the subpath of your site, e.g. /blog
url: "https://y.lyxw.xyz" # 你的域名
page_no_title: "No title" # 文章无标题时默认显示内容
beian: # "备案号"
email: xluoying2017@gmail.com
permalink: /:title

# Build settings
markdown: kramdown
gems: [jekyll-paginate]

github_username: shiokiri
twitter_username:

# Pageinate settings
paginate: 15 # 分页大小
paginate_path: ":num"

# Search settings
baidu_search: false
google_search: false

# Menu settings
menu:
  - page: 首页
    directory: .
    icon: icon-home
  - page: 归档
    directory: archives/
    icon: icon-archive
  # - page: 关于
  #   directory: about/
  #   icon: icon-about
  # - page: 历史
  #   directory: history/
  #   icon: icon-history
  # - page: 订阅
  #   directory: feed.xml
  #   icon: icon-rss

# Link settings
links: # 友情链接